using FaceAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.HttpOverrides;
using Pgvector.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<PgDbContext>(options =>
    options.UseNpgsql(
        connectionString,
        o => o.UseVector()));

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Mở CORS cho phép Web App gọi API
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll",
        p => p.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
});

builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders =
        ForwardedHeaders.XForwardedFor |
        ForwardedHeaders.XForwardedProto;
    options.KnownProxies.Add(System.Net.IPAddress.Loopback);
    options.KnownProxies.Add(System.Net.IPAddress.IPv6Loopback);
    options.KnownProxies.Add(
        System.Net.IPAddress.Parse("::ffff:127.0.0.1"));
});

var app = builder.Build();

app.UseForwardedHeaders();

// Tự động khởi tạo Database Schema
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<PgDbContext>();
    db.Database.EnsureCreated();
    db.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "AttendanceHistories" (
            "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "UserId" integer NOT NULL,
            "UserCode" text NOT NULL,
            "FullName" text NOT NULL,
            "CheckedInAtUtc" timestamp with time zone NOT NULL,
            "IpAddress" text NULL,
            "IpAddressV4" text NULL,
            "IpAddressV6" text NULL,
            "UserAgent" text NULL,
            CONSTRAINT "FK_AttendanceHistories_Users_UserId"
                FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
        );

        CREATE INDEX IF NOT EXISTS "IX_AttendanceHistories_CheckedInAtUtc"
            ON "AttendanceHistories" ("CheckedInAtUtc");

        ALTER TABLE "AttendanceHistories"
            ADD COLUMN IF NOT EXISTS "IpAddressV4" text NULL;

        ALTER TABLE "AttendanceHistories"
            ADD COLUMN IF NOT EXISTS "IpAddressV6" text NULL;
        """);
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("AllowAll");
app.UseAuthorization();
app.MapControllers();

app.Run();